GCO/Models/ErrorViewModel.cs
using System;

namespace GCO.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GCO/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Servico.Tabelas;

namespace GCO.Controllers
{
    public class DashboardController : Controller
    {
        private DashboardServico dashboardServico = new DashboardServico();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ObterDados()
        {
            ViewBag.QtdOcorrencias = dashboardServico.ObterQuantidadeOcorrenciaStatusAberto();

            return Json(ViewBag.QtdOcorrencias);
        }
    }
}

GCO/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GCO.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

GCO/Controllers/OcorrenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Modelo.Entidades;
using Servico.Entidades;
using Servico.Tabelas;
using System.Net;

namespace GCO.Controllers
{
    public class OcorrenciaController : Controller
    {
        private OcorrenciaServico ocorrenciaServico = new OcorrenciaServico();
        private IteracaoOcorrenciaServico iteracaoServico = new IteracaoOcorrenciaServico();

        // Métodos do Controlador Ocorrencia
        private ActionResult GravarOcorrencia(Ocorrencia ocorrencia)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ocorrencia.NumeroOcorrencia = ocorrenciaServico.GerarNumeroOcorrencia();
                    ocorrencia.StatusOcorrencia = 0;
                    ocorrencia.DataHora = DateTime.Now;
                    ocorrenciaServico.GravarOcorrencia(ocorrencia);
                    return RedirectToAction("ConsultarOcorrencia");
                }
                return View(ocorrencia);
            }
            catch
            {
                return View(ocorrencia);
            }
        }

        private ActionResult ObterVisaoOcorrenciaPorId(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ocorrencia produto = ocorrenciaServico.ObterOcorrenciaPorId((long)id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        [HttpGet]
        public ActionResult ConsultarOcorrencia()
        {
            return View(ocorrenciaServico.ObterOcorrenciasClassificadasPorDataHora());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdicionarOcorrencia()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdicionarOcorrencia(Ocorrencia ocorrencia)
        {
            if (ocorrencia != null)
            {
                return GravarOcorrencia(ocorrencia);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DetalharOcorrencia(long? id)
        {
            return ObterVisaoOcorrenciaPorId(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ListarIteracoes(long? Id)
        {
            var iteracoes = iteracaoServico.ObterIteracoes(Id);
            return Json(iteracoes);
        }

        //[HttpPost]
        //public ActionResult AdicionarIteracoes(IteracaoOcorrencia iteracao)
        //{

        //    return iteracaoServico.GravarIteracao(iteracao);

        //}

    }
}
}

GCO/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

GCO/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

GCO/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="pt-br" class="no-focus">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    @RenderSection("styles", false)

    <!-- Icons -->
    <link rel="shortcut icon" href="/assets/media/favicons/favicon.png">
    <link rel="icon" type="image/png" sizes="192x192" href="Template/assets/media/favicons/favicon-192x192.png">
    <link rel="apple-touch-icon" sizes="180x180" href="Template/assets/media/favicons/apple-touch-icon-180x180.png">
    <link href="~/Template/assets/fonts/fontawesome 5.3/css/fontawesome-all.min.css" rel="stylesheet" />
    <!-- END Icons -->
    <!-- Stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,400i,600,700">
    <link rel="stylesheet" id="css-main" href="@Url.Content("~/Template/assets/css/codebase.min.css")">
    <!-- END Stylesheets -->
</head>
<body>
    <div id="page-container" class="sidebar-inverse side-scroll page-header-fixed page-header-inverse main-content-boxed">
        <!-- Header -->
        <header id="page-header">
            <!-- Header Content -->
            <div class="content-header">
                <!-- Left Section -->
                <div class="content-header-section">
                    <!-- Logo -->
                    <div class="content-header-item">
                        @*<a class=" font-w700 mr-5" href="@Url.Action("Index","Home")">
                                <img src="~/Content/img/blacklogo.png" />
                            </a>*@
                    </div>
                    <!-- END Logo -->
                </div>
                <!-- END Left Section -->
                <!-- Middle Section -->
                <div class="content-header-section d-none d-lg-block">
                    <!-- Header Navigation -->
                    <ul class="nav-main-header">
                        <li>
                            <a href="@Url.Action("Index","Dashboard")"><i class="si si-compass"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarCheckList","CheckList")"><i class="fas fa-check-square"></i>CheckList</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarOcorrencia","Ocorrencia")"><i class="fas fa-exclamation-triangle"></i>Ocorrências</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarServidor","Servidor")"><i class="fas fa-server"></i>Servidores</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarContato","Contato")"><i class="fas fa-phone-square"></i>Contatos</a>
                        </li>
                    </ul>
                    <!-- END Header Navigation -->
                </div>
                <!-- Right Section -->
                <div class="content-header-section">
                    <!-- Color Themes + A few of the many header options (used just for demonstration) -->
                    <!-- Themes functionality initialized in Template._uiHandleTheme() -->
                    <!-- END Color Themes + A few of the many header options -->
                    <!-- Open Search Section -->
                    <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                    <!-- END Open Search Section -->
                    <!-- Toggle Sidebar -->
                    <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                    <!-- END Toggle Sidebar -->
                </div>
                <!-- END Right Section -->
            </div>
            <!-- END Header Content -->
            <!-- Header Search -->
            <!-- END Header Search -->
            <!-- Header Loader -->
            <!-- Please check out the Activity page under Elements category to see examples of showing/hiding it -->
            <div id="page-header-loader" class="overlay-header bg-primary">
                <div class="content-header content-header-fullrow text-center">
                    <div class="content-header-item">
                        <i class="fa fa-sun-o fa-spin text-white"></i>
                    </div>
                </div>
            </div>
            <!-- END Header Loader -->
        </header>
        <!-- END Header -->
        <!-- Main Container -->
        <main id="main-container">
            @RenderBody()
            <!-- Page Content -->
            <!-- END Page Content -->

        </main>
        <!-- END Main Container -->
        <!-- Footer -->
        @*<footer id="page-footer" class="opacity-0">
                <div class="content py-20 font-size-xs clearfix">
                    <div class="float-right">
                        Crafted with <i class="fa fa-heart text-pulse"></i> by <a class="font-w600" href="https://1.envato.market/ydb" target="_blank">pixelcave</a>
                    </div>
                    <div class="float-left">
                        <a class="font-w600" href="#" target="_blank">Codebase 3.0</a> &copy; <span class="js-year-copy">2017</span>
                    </div>
                </div>
            </footer>*@
        <!-- END Footer -->
    </div>
    <!-- END Page Container -->
    <!-- Page JS Plugins -->
    <script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @*<script src="@Url.Content("~/Template/assets/js/plugins/chartjs/Chart.bundle.min.js")"></script>*@

    <!-- Page JS Code -->
    <script src="@Url.Content("~/Template/assets/js/codebase.core.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/codebase.app.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/pages/be_pages_dashboard.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/plugins/chartjs/Chart.min.js")"></script>

    @RenderSection("ScriptPage", false);
</body>
</html>